spring.application.name=healthCare

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=12345678
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bns-ssl
server.port=8443


# OAuth2 Client ??
fitbit.client-id=23RYJV
fitbit.client-secret=5875b8dbb5e2d91e40797358414858b3
fitbit.redirect-uri=https://localhost:8443/callback
fitbit.authorization-uri=https://www.fitbit.com/oauth2/authorize
fitbit.token-uri=https://api.fitbit.com/oauth2/token
spring.security.oauth2.client.registration.fitbit.client-id=${fitbit.client-id}
spring.security.oauth2.client.registration.fitbit.client-secret=${fitbit.client-secret}
spring.security.oauth2.client.registration.fitbit.redirect-uri=${fitbit.redirect-uri}
spring.security.oauth2.client.registration.fitbit.authorization-uri=${fitbit.authorization-uri}
spring.security.oauth2.client.registration.fitbit.token-uri=${fitbit.token-uri}
spring.security.oauth2.client.registration.fitbit.scope=activity,heartrate,sleep,location,nutrition,oxygen_saturation,profile,respiratory_rate,settings,sleep,social,temperature,weight
spring.security.oauth2.client.registration.fitbit.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.fitbit.authorization-uri=${fitbit.authorization-uri}
spring.security.oauth2.client.provider.fitbit.token-uri=${fitbit.token-uri}
spring.security.oauth2.client.provider.fitbit.jwk-set-uri=https://api.fitbit.com/.well-known/jwks.json

# OAuth2 Provider ??
spring.security.oauth2.client.provider.fitbit.user-info-uri=https://api.fitbit.com/1/user/-/profile.json

# ?? ??
#server.port=8000